[build-system]
requires = [
    "setuptools>=50.3.1",
    "numpy>=1.14.5",
    "matplotlib>=3.3.4",
    "pandas>=0.23.3",
    "scipy>=1.6.0",
    "scikit-learn>=0.24.1",
	"numpydoc>=1.5.0",
]
build-backend = "setuptools.build_meta"